package com.test.demo.util;

public enum MisfireInstructionType {
     None ("",0),
     MISFIRE_INSTRUCTION_FIRE_NOW("MISFIRE_INSTRUCTION_FIRE_NOW",1),
     MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT("MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_EXISTING_REPEAT_COUNT",2),
     MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT("MISFIRE_INSTRUCTION_RESCHEDULE_NOW_WITH_REMAINING_REPEAT_COUNT",3),
     MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT("MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT",4),
     MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT("MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_EXISTING_COUNT",5),
     MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY("MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY",-1);


     private final String key;
     private final Integer value;

     MisfireInstructionType(String key, Integer value) {
          this.key = key;
          this.value = value;
     }

     public String getKey() {
          return key;
     }
     public Integer getValue() {
          return value;
     }
}
